services:
  - type: web
    name: loan-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    workingDir: backend
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free